// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { FilesUploadFileData, FilesUploadFileResponse, FilesReadFilesData, FilesReadFilesResponse, FilesDownloadFileData, FilesDownloadFileResponse, FilesDeleteFileData, FilesDeleteFileResponse, JobsEnqueueUsersExportResponse, JobsReadJobData, JobsReadJobResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginRefreshAccessTokenData, LoginRefreshAccessTokenResponse, LoginLogoutAllResponse, LoginDemoCredentialsResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PlatformReadRolesData, PlatformReadRolesResponse, PlatformCreateRoleData, PlatformCreateRoleResponse, PlatformReadRolePermissionsData, PlatformReadRolePermissionsResponse, PlatformUpdateUserRolesData, PlatformUpdateUserRolesResponse, PlatformReadUserRolesData, PlatformReadUserRolesResponse, PlatformReadAuditLogsData, PlatformReadAuditLogsResponse, PrivateCreateUserData, PrivateCreateUserResponse, SettingsReadSettingsResponse, SettingsUpdateSettingData, SettingsUpdateSettingResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersExportUsersResponse, UsersImportUsersData, UsersImportUsersResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, UtilsReadyCheckResponse } from './types.gen';

export class FilesService {
    /**
     * Upload File
     * @param data The data for the request.
     * @param data.formData
     * @returns FileAssetPublic Successful Response
     * @throws ApiError
     */
    public static uploadFile(data: FilesUploadFileData): CancelablePromise<FilesUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Files
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns FileAssetPublic Successful Response
     * @throws ApiError
     */
    public static readFiles(data: FilesReadFilesData = {}): CancelablePromise<FilesReadFilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Download File
     * @param data The data for the request.
     * @param data.assetId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadFile(data: FilesDownloadFileData): CancelablePromise<FilesDownloadFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/{asset_id}',
            path: {
                asset_id: data.assetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete File
     * @param data The data for the request.
     * @param data.assetId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteFile(data: FilesDeleteFileData): CancelablePromise<FilesDeleteFileResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/files/{asset_id}',
            path: {
                asset_id: data.assetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class JobsService {
    /**
     * Enqueue Users Export
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static enqueueUsersExport(): CancelablePromise<JobsEnqueueUsersExportResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/jobs/users-export'
        });
    }
    
    /**
     * Read Job
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static readJob(data: JobsReadJobData): CancelablePromise<JobsReadJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh Access Token
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static refreshAccessToken(data: LoginRefreshAccessTokenData): CancelablePromise<LoginRefreshAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/refresh',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Logout All
     * Revoke all existing access tokens for the current user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static logoutAll(): CancelablePromise<LoginLogoutAllResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/logout-all'
        });
    }
    
    /**
     * Demo Credentials
     * Return local-only demo credentials for the development login page.
     * @returns DemoCredentials Successful Response
     * @throws ApiError
     */
    public static demoCredentials(): CancelablePromise<LoginDemoCredentialsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/login/demo-credentials'
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PlatformService {
    /**
     * Read Roles
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns RolesPublic Successful Response
     * @throws ApiError
     */
    public static readRoles(data: PlatformReadRolesData = {}): CancelablePromise<PlatformReadRolesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/roles',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Role
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static createRole(data: PlatformCreateRoleData): CancelablePromise<PlatformCreateRoleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/roles',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Role Permissions
     * @param data The data for the request.
     * @param data.roleId
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static readRolePermissions(data: PlatformReadRolePermissionsData): CancelablePromise<PlatformReadRolePermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/roles/{role_id}/permissions',
            path: {
                role_id: data.roleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User Roles
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserRolesPublic Successful Response
     * @throws ApiError
     */
    public static updateUserRoles(data: PlatformUpdateUserRolesData): CancelablePromise<PlatformUpdateUserRolesResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/users/{user_id}/roles',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Roles
     * @param data The data for the request.
     * @param data.userId
     * @returns UserRolesPublic Successful Response
     * @throws ApiError
     */
    public static readUserRoles(data: PlatformReadUserRolesData): CancelablePromise<PlatformReadUserRolesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}/roles',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Audit Logs
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns AuditLogsPublic Successful Response
     * @throws ApiError
     */
    public static readAuditLogs(data: PlatformReadAuditLogsData = {}): CancelablePromise<PlatformReadAuditLogsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/audit-logs',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SettingsService {
    /**
     * Read Settings
     * @returns SystemSettingPublic Successful Response
     * @throws ApiError
     */
    public static readSettings(): CancelablePromise<SettingsReadSettingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/settings/'
        });
    }
    
    /**
     * Update Setting
     * @param data The data for the request.
     * @param data.key
     * @param data.requestBody
     * @returns SystemSettingPublic Successful Response
     * @throws ApiError
     */
    public static updateSetting(data: SettingsUpdateSettingData): CancelablePromise<SettingsUpdateSettingResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/settings/{key}',
            path: {
                key: data.key
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Export Users
     * Export non-sensitive user fields as UTF-8 CSV.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static exportUsers(): CancelablePromise<UsersExportUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/export.csv'
        });
    }
    
    /**
     * Import Users
     * Import users from CSV columns: email,password,full_name,is_active.
     * @param data The data for the request.
     * @param data.formData
     * @returns UserImportResult Successful Response
     * @throws ApiError
     */
    public static importUsers(data: UsersImportUsersData): CancelablePromise<UsersImportUsersResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/import.csv',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * 轻量存活检查（liveness）：进程能响应即返回 True，不触碰数据库。
     * 容器重启判定、负载均衡存活探针用它。
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
    /**
     * Ready Check
     * Bound the full database probe; expose no connection details on failure.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static readyCheck(): CancelablePromise<UtilsReadyCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/ready-check/'
        });
    }
}