// This file is auto-generated by @hey-api/openapi-ts

export type AuditLogPublic = {
    id: string;
    actor_user_id?: (string | null);
    action: string;
    resource_type: string;
    resource_id?: (string | null);
    details?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type Body_files_upload_file = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_users_import_users = {
    file: string;
};

export type DemoCredentials = {
    username: string;
    password: string;
};

export type FileAssetPublic = {
    id: string;
    original_name: string;
    content_type?: (string | null);
    size: number;
    owner_user_id?: (string | null);
    created_at?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type JobPublic = {
    id: string;
    task_type: string;
    status: string;
    owner_user_id?: (string | null);
    result?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    created_at?: (string | null);
    finished_at?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PermissionPublic = {
    codename: string;
    description?: (string | null);
    id: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
};

export type RolePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type SystemSettingPublic = {
    key: string;
    value: string;
    description?: (string | null);
    updated_at?: (string | null);
};

export type SystemSettingUpdate = {
    value: string;
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserImportResult = {
    created_count: number;
    errors: Array<(string)>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRolesPublic = {
    data: Array<RolePublic>;
};

export type UserRolesUpdate = {
    role_ids: Array<(string)>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (FileAssetPublic);

export type FilesReadFilesData = {
    limit?: number;
    skip?: number;
};

export type FilesReadFilesResponse = (Array<FileAssetPublic>);

export type FilesDownloadFileData = {
    assetId: string;
};

export type FilesDownloadFileResponse = (unknown);

export type FilesDeleteFileData = {
    assetId: string;
};

export type FilesDeleteFileResponse = (void);

export type JobsEnqueueUsersExportResponse = (JobPublic);

export type JobsReadJobData = {
    jobId: string;
};

export type JobsReadJobResponse = (JobPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshAccessTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutAllResponse = (Message);

export type LoginDemoCredentialsResponse = (DemoCredentials);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PlatformReadRolesData = {
    limit?: number;
    skip?: number;
};

export type PlatformReadRolesResponse = (RolesPublic);

export type PlatformCreateRoleData = {
    requestBody: RoleCreate;
};

export type PlatformCreateRoleResponse = (RolePublic);

export type PlatformReadRolePermissionsData = {
    roleId: string;
};

export type PlatformReadRolePermissionsResponse = (Array<PermissionPublic>);

export type PlatformUpdateUserRolesData = {
    requestBody: UserRolesUpdate;
    userId: string;
};

export type PlatformUpdateUserRolesResponse = (UserRolesPublic);

export type PlatformReadUserRolesData = {
    userId: string;
};

export type PlatformReadUserRolesResponse = (UserRolesPublic);

export type PlatformReadAuditLogsData = {
    limit?: number;
    skip?: number;
};

export type PlatformReadAuditLogsResponse = (AuditLogsPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SettingsReadSettingsResponse = (Array<SystemSettingPublic>);

export type SettingsUpdateSettingData = {
    key: string;
    requestBody: SystemSettingUpdate;
};

export type SettingsUpdateSettingResponse = (SystemSettingPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersExportUsersResponse = (unknown);

export type UsersImportUsersData = {
    formData: Body_users_import_users;
};

export type UsersImportUsersResponse = (UserImportResult);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadyCheckResponse = (Message);