// This file is auto-generated by @hey-api/openapi-ts

export type AccessPublic = {
    pages: Array<PageAccessPublic>;
    permissions: Array<(string)>;
    is_admin: boolean;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DemoCredentials = {
    username: string;
    password: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PageAccessPublic = {
    path: string;
    codename: string;
    title: string;
    admin_only: boolean;
    allowed: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
};

export type RoleDetailPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
    permissions: Array<(string)>;
    is_default: boolean;
    user_count: number;
};

export type RolePermissionsUpdate = {
    permissions: Array<(string)>;
};

export type RolePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRolesPublic = {
    data: Array<RolePublic>;
};

export type UserRolesUpdate = {
    role_ids: Array<(string)>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AccessReadAccessResponse = (AccessPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshAccessTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutAllResponse = (Message);

export type LoginDemoCredentialsResponse = (DemoCredentials);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RolesDeleteRoleData = {
    roleId: string;
};

export type RolesDeleteRoleResponse = (Message);

export type RolesReadRolesResponse = (Array<RoleDetailPublic>);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RoleDetailPublic);

export type RolesUpdatePermissionsData = {
    requestBody: RolePermissionsUpdate;
    roleId: string;
};

export type RolesUpdatePermissionsResponse = (RoleDetailPublic);

export type RolesReadUserRolesData = {
    userId: string;
};

export type RolesReadUserRolesResponse = (UserRolesPublic);

export type RolesUpdateUserRolesData = {
    requestBody: UserRolesUpdate;
    userId: string;
};

export type RolesUpdateUserRolesResponse = (UserRolesPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadyCheckResponse = (Message);